#!/usr/bin/env sh

# Colors
NC='\033[0m'
BBlue='\033[1;34m'
BRed='\033[1;31m'

REGEX_ISSUE_ID="[a-zA-Z0-9,\.\-]+-[0-9]+"
BRANCH_NAME=$(git symbolic-ref --short HEAD)
ISSUE_ID=$(echo "$BRANCH_NAME" | grep -o -E "$REGEX_ISSUE_ID")
COMMIT_MESSAGE=$(cat "$1")

if [ -z "$ISSUE_ID" ]; then
	echo -e "${BRed}The branch is not in the standard it should be, master... ${NC}"
	exit 1
fi


# Prevent adding a issue key in commits that already have a JIRA issue key
# e.g. investplusplus-1: investplusplus-1 - My feature

# if [[ $COMMIT_MESSAGE == $ISSUE_ID* ]]; then
if [ "$(echo "$COMMIT_MESSAGE" | grep -E "^$ISSUE_ID")" ]; then
    exit 0
fi

echo "$ISSUE_ID: $COMMIT_MESSAGE" >$1
